import type { Property } from '@/lib/types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  const image = PlaceHolderImages.find(p => p.id === id);
  return {
    imageUrl: image?.imageUrl || 'https://picsum.photos/seed/error/800/600',
    imageHint: image?.imageHint || 'placeholder'
  };
};

export const properties: Property[] = [
  {
    id: 'prop-1',
    title: 'Modern Luxury Apartment',
    type: 'Residential',
    location: 'Koramangala',
    city: 'Bangalore',
    price: 25000000,
    size: 1800,
    bedrooms: 3,
    bathrooms: 3,
    ...getImage('prop-1'),
  },
  {
    id: 'prop-2',
    title: 'Spacious Suburban Villa',
    type: 'Residential',
    location: 'Jubilee Hills',
    city: 'Hyderabad',
    price: 45000000,
    size: 3200,
    bedrooms: 4,
    bathrooms: 5,
    ...getImage('prop-2'),
  },
  {
    id: 'prop-3',
    title: 'Prime Commercial Space',
    type: 'Commercial',
    location: 'Bandra Kurla Complex',
    city: 'Mumbai',
    price: 120000000,
    size: 2500,
    ...getImage('prop-3'),
  },
  {
    id: 'prop-4',
    title: 'Residential Plot',
    type: 'Plot',
    location: 'Hinjewadi',
    city: 'Pune',
    price: 8000000,
    size: 2000,
    ...getImage('prop-4'),
  },
  {
    id: 'prop-5',
    title: 'Cozy 2BHK for Rent',
    type: 'Rental',
    location: 'Adyar',
    city: 'Chennai',
    price: 35000,
    size: 1100,
    bedrooms: 2,
    bathrooms: 2,
    ...getImage('prop-5'),
  },
  {
    id: 'prop-6',
    title: 'Sea-View Villa',
    type: 'Residential',
    location: 'Juhu',
    city: 'Mumbai',
    price: 85000000,
    size: 4000,
    bedrooms: 5,
    bathrooms: 6,
    ...getImage('prop-6'),
  },
  {
    id: 'prop-7',
    title: 'High-Rise Flat',
    type: 'Residential',
    location: 'Sector 62',
    city: 'Delhi',
    price: 18000000,
    size: 1600,
    bedrooms: 3,
    bathrooms: 2,
    ...getImage('prop-7'),
  },
  {
    id: 'prop-8',
    title: 'IT Park Office',
    type: 'Commercial',
    location: 'Hitec City',
    city: 'Hyderabad',
    price: 50000,
    size: 1500,
    ...getImage('prop-8'),
  },
  {
    id: 'prop-9',
    title: 'Luxury Penthouse',
    type: 'Residential',
    location: 'Whitefield',
    city: 'Bangalore',
    price: 32000000,
    size: 2500,
    bedrooms: 4,
    bathrooms: 4,
    ...getImage('prop-9'),
  },
  {
    id: 'prop-10',
    title: 'Traditional Bungalow',
    type: 'Residential',
    location: 'Salt Lake',
    city: 'Kolkata',
    price: 22000000,
    size: 2800,
    bedrooms: 4,
    bathrooms: 3,
    ...getImage('prop-10'),
  },
  {
    id: 'prop-11',
    title: 'Agricultural Farmland',
    type: 'Plot',
    location: 'Lonavala',
    city: 'Pune',
    price: 15000000,
    size: 43560, // 1 acre
    ...getImage('prop-11'),
  },
  {
    id: 'prop-12',
    title: 'Studio Apartment for Rent',
    type: 'Rental',
    location: 'Koregaon Park',
    city: 'Pune',
    price: 22000,
    size: 600,
    bedrooms: 1,
    bathrooms: 1,
    ...getImage('prop-12'),
  },
];

export const propertyTypes = ['Residential', 'Commercial', 'Plot', 'Rental'];
export const cities = ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Pune', 'Chennai', 'Kolkata', 'Ahmedabad'];
